import argparse 

parser=argparse.ArgumentParser(description="Color and Depth Video Inpainting") 
parser.add_argument('--project_name',type=str,default="Color and Depth Video Inpainting") 
parser.add_argument("--seed",type=int,default=1121)
parser.add_argument("--resume",type=bool,default=True)
parser.add_argument("--weight_gen",type=str,default='model.pth')
parser.add_argument("--weight_dis",type=str,default='d.pth')
parser.add_argument("--lr",type=float,default=1e-4)
parser.add_argument("--weight_decay",type=float,default=1e-4)
parser.add_argument("--momentum",type=float,default=0.5)
parser.add_argument("--epoch",type=int,default=1000)
parser.add_argument("--train_batch_size",type=int,default=1)
parser.add_argument("--test_batch_size",type=int,default=1)
parser.add_argument("--model_name",type=str,default='model')
parser.add_argument("--dis_name",type=str,default='d')
parser.add_argument("--save_fre",type=int,default=50)
parser.add_argument('--DDP', action="store_true")
parser.add_argument("--local_rank", default=-1, type=int)
parser.add_argument("--read", default="", type=str)
parser.add_argument("--ckpt", default=False, type=bool) 
parser.add_argument("--num_workers", default=0) 